# Generated by Django 3.2 on 2023-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230324_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
