# Generated by Django 3.2 on 2023-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_adress1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_adress2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='Order',
            new_name='order',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
